[build.environment]
  NODE_VERSION = "18"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = ".vitepress/dist"
  command = "pnpm run build"

[[redirects]]
  from = "/new"
  to = "https://stackblitz.com/github/nyxb/kolibry-new?file=slides.md"
  status = 302
  force = true

[[redirects]]
  from = "https://kolibry.nyxb.nexus/*"
  to = "https://kolibry.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/demo/composable-vue/*"
  to = "https://demo.kolibry.dev/composable-vue"
  status = 301
  force = true

[[redirects]]
  from = "/demo/starter/*"
  to = "https://demo.kolibry.dev/starter"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
